### ISSUE TITLE
Incompatibility between dynamic and static configurations

### ISSUE THREAD

**Issue by drug007** [Timu5/bindbc-nuklear#5]
compiling of the demo using static configuration demands sources changes that are incompatible with dynamic configuration. For example the dynamic configuration defines all nuklear functions as function pointers but the static configuration defines functions like functions (see the last argument `nk_filter_float`, [original](https://github.com/Timu5/bindbc-nuklear/blob/dd89ab6c9098f691fd7fecac5cfd7efe7a3497dc/demo/source/calculator.d#L30) from demo):

dynamic configuration
```
nk_edit_string(ctx, NK_EDIT_SIMPLE, buffer.ptr, &len, 255, nk_filter_float); // here nk_filter_float is a function pointer
```
static configuration
```
nk_edit_string(ctx, NK_EDIT_SIMPLE, buffer.ptr, &len, 255, &nk_filter_float); // nk_filter_float is a function so address taking
```

This makes changing of configuration really annoying. Wouldn't using functions instead of functions pointers in dynamic configuration as in static one be more suitable?

**Comment by Timu5** [comment]
I'm not really sure if its possible to move from function to function pointers when using bindbc-loader.  One potential solution could be to use function pointers for this few functions in static configuration.

**Comment by drug007** [comment]
I'm new to bindbc philosophy but I did the following:
```
    pnk_filter_float *nk_filter_float; // dereference pointer
```
I'm still experementing though

**Comment by drug007** [comment]
I was wrong about 'dereferencing' function pointer. 

So now I see two ways to eliminate distinction between dynamic and static configurations:
1. change API in the way that user code will be the same for different configurations
2. in static configuration make these `filter` functions function pointers like in dynamic configuration

None of these way is good for me but probably second has less disadvantages than first

**Comment by Timu5** [comment]
I think it should works fine now.

**Comment by drug007** [comment]
Yes, this is exactly what I've done.

**Comment by drug007** [comment]
Only the block of function pointers should be wrapped by `__gshared` to prevent linking error.

**Comment by drug007** [comment]
it happened to be only partial solution because this symbols are defined twice - both in d bindings and in nuklear library itself. if one links both d bindings and nuklear statically then multiple definitions linking error occurs.
