### ISSUE TITLE
jak narysować coś na desktopie

### ISSUE THREAD

**Issue by sp00ck** [Timu5/bindbc-nuklear#7]
W jaki sposób w C narysować linie np. zieloną w tle wszystkich okien. Nie w oknie ale na backgroundzie ;)

**Comment by Timu5** [comment]
Masz na mysli okna nuklear'a czy okna systemowe?

**Comment by sp00ck** [comment]
w oknie na samym dole wszystkich innych okien
w tle, nie oknach nucleara
![aaaaaaaaaa](https://user-images.githubusercontent.com/25770302/64421752-91bef100-d0a2-11e9-9544-01c0a331f882.png)

**Comment by Timu5** [comment]
Jako tako nuklear oferuje tylko rysowanie na oknach, zatem aby uzyskać taki efekt trzeba albo rysować sobie samemu np w opengl i później rysować okna nuklear albo utworzyć sobie okno w tle, bez dekoracji i rysować sobie na nim prymitywy. Nuklear posiada szereg funkcji do rysowania prymitywów zaczynających się od nk_stroke_*, nk_fill_* jak i również nk_draw_image do obrazków i nk_draw_text dla tekstu. Przykład jak uzyskać taki efekt(napisany w D):
`

    nk_style_window old = ctx.style.window; // save current window style
    ctx.style.window.spacing = nk_vec2(0, 0); // no spacing
    ctx.style.window.padding = nk_vec2(0, 0); // no padding
    ctx.style.window.fixed_background = nk_style_item_color(nk_rgb(255,255,255)); // white color
		
    if (nk_begin(ctx, "Background", nk_rect(0, 0, 1280, 800), NK_WINDOW_NO_SCROLLBAR | NK_WINDOW_BACKGROUND | NK_WINDOW_NO_INPUT))
    {
        nk_stroke_line(&ctx.current.buffer, 0, 0, 1280, 800, 2, nk_rgb(255,0,0));  // red line
        nk_stroke_line(&ctx.current.buffer, 0, 800, 1280, 0, 2, nk_rgb(255,0,0)); // red line
        nk_fill_rect(&ctx.current.buffer, nk_rect(150, 10, 150, 150), 1, nk_rgb(255,0,255)); // pink rectangle
    }
    nk_end(ctx);

    ctx.style.window = old; // restore window style

`

![nuklear_background](https://user-images.githubusercontent.com/5563731/64444915-7faa7600-d0d5-11e9-8629-ab15b6309227.png)

**Comment by sp00ck** [comment]
Bardzo dziękuję za odpowiedź.
Próbowałem pisac bezpośrednio w opengl , niby tylko linie i trójkąty, ale wymiękłem. Nie umiem tego zrobić tak by nie wywalało sie samo demo. Może Ty umiesz?

1. Jest przykład pisania po 'canvas'  example/canvas.c ale nigdy mi się nie udałe tego dokonać. Robi coś podobnego, zapamietuje kontekst i potem coś rysuje i odtwarza kontekst.
2. Powinny być jakies głebsze prymitywy niż nk_stroke_line()
Jeśli dobrze myślę, to gdyby były takie podstawowe funkcje to można było by je wstawić
```
plik demo.c ale powinno działac i w D
        /* Draw */
        SDL_GetWindowSize(win, &win_width, &win_height);
        glViewport(0, 0, win_width, win_height);
        glClear(GL_COLOR_BUFFER_BIT);
        glClearColor(bg.r, bg.g, bg.b, bg.a);
```
i tu wstawić te instrukcje prymityw_linia(desktop,....);
a przed 
```
nk_sdl_render(NK_ANTI_ALIASING_ON, MAX_VERTEX_MEMORY, MAX_ELEMENT_MEMORY);
        SDL_GL_SwapWindow(win);
```
Myślę, że dowolna biblioteka gdyby miała taką funkcjonalnosc pozwoliła by tworzyć jakis program i okna były by tylko do trybu admin lub edycja. Nie zawsze program (np. gra potrzebuje okienek) a nie zawsze program wymaga edycji elementów.
Tylko nie udało mi się wstawić tam tych prymitywów po wyczyszczeniu ekranu.

w C to by było jakos tak?
nk_stroke_line((struct nk_command_buffer *)&(ctx->current->buffer), 0, 0, 1280, 800, 2, nk_rgb(255,0,0));
jeśli dobrze rozumiem to ten buffor jest najważniejszy, gdybym miał do niego dostęp.
3. Dodanie okna bez ramek (i jak rozumiem bez możliwości przenoszenia) jest ciekawe, ale czy dało by się znać rozmiar okna głównego? W końcu okienka nukleara nie wiedzą czy nie wychodza po za okno.
